grafana:
  adminPassword: "securepassword"
  service:
    type: NodePort                        
  ingress:
    enabled: false                        
prometheus:
  prometheusSpec:
    additionalScrapeConfigs:
      - job_name: windows-vm
        metrics_path: /metrics
        static_configs:
        - targets: ['82.212.97.194:9182']
    retention: 15d
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: longhorn    
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 20Gi
