apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: frontend-catchall
  namespace: frontend 
spec:
  gateways:
  - istio-system/web-gw
  hosts:
  - "*"
  http:
  - match:
    - uri: { prefix: "/" } 
    rewrite: { uri: "/" } 
    route:
    - destination:
        host: frontend-service.frontend.svc.cluster.local
        port: { number: 80 }
