apiVersion: v1
kind: Namespace
metadata:
  name: product-service
  labels:
    istio-injection: enabled

---

apiVersion: v1
kind: Secret
metadata:
  name: product-secret
  namespace: product-service
type: Opaque
stringData:
  DATABASE_URL: postgresql://product_user:product_pass@product-db.product-service.svc.cluster.local:5432/product_db
  JWT_SECRET_KEY: supersecretkey

---
apiVersion: v1
kind: Service
metadata:
  name: product-db
  namespace: product-service
spec:
  clusterIP: None
  selector:
    app: product-db
  ports:
  - name: tcp-postgres
    port: 5432
    targetPort: 5432
    protocol: TCP

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: product-db-pvc
  namespace: product-service
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: product-db
  namespace: product-service
spec:
  serviceName: product-db
  replicas: 1
  selector:
    matchLabels:
      app: product-db
  template:
    metadata:
      labels:
        app: product-db
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values: ["product-db"]
                topologyKey: "kubernetes.io/hostname"
      tolerations:
        - key: "node.kubernetes.io/not-ready"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 60
      containers:
      - name: postgres
        image: postgres:14
        env:
        - name: POSTGRES_DB
          value: product_db
        - name: POSTGRES_USER
          value: product_user
        - name: POSTGRES_PASSWORD
          value: product_pass
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        ports:
        - containerPort: 5432
          name: tcp-postgres
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
---

apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: product-service
spec:
  selector:
    app: product
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 5000
    - name: http-int
      protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-deployment
  namespace: product-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      annotations:
        traffic.sidecar.istio.io/includeInboundPorts: "80,5000"
      labels:
        app: product
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - product
                topologyKey: "kubernetes.io/hostname"
      tolerations:
        - key: "node.kubernetes.io/not-ready"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 60
      containers:
      - name: product
        image: juidas/product-service:v1.0.10
        ports:
        - containerPort: 5000
          name: http
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: product-secret
              key: DATABASE_URL
        - name: JWT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: product-secret
              key: JWT_SECRET_KEY

