apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: product-pod-kill
  namespace: chaos-mesh
spec:
  action: pod-kill
  mode: one
  selector:
    namespaces: ["product-service"]
  duration: "30s"
