apiVersion: v1
kind: Namespace
metadata:
  name: cart-service
  labels:
    istio-injection: enabled

---

apiVersion: v1
kind: Secret
metadata:
  name: cart-secret
  namespace: cart-service
type: Opaque
stringData:
  JWT_SECRET_KEY: "supersecretkey"
  PRODUCT_SERVICE_URL: "http://product-service.product-service.svc.cluster.local/products/"

---

apiVersion: v1
kind: Service
metadata:
  name: cart-service
  namespace: cart-service
spec:
  selector:
    app: cart
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 5000
    - name: http-int
      protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-deployment
  namespace: cart-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart
  template:
    metadata:
      annotations:
        traffic.sidecar.istio.io/includeInboundPorts: "80,5000"
      labels:
        app: cart
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - cart
                topologyKey: "kubernetes.io/hostname"
      tolerations:
        - key: "node.kubernetes.io/not-ready"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 60
      containers:
      - name: cart
        image: juidas/cart-service:v1.0.8
        ports:
        - containerPort: 5000
          name: http
        env:
        - name: JWT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: cart-secret
              key: JWT_SECRET_KEY
        - name: PRODUCT_SERVICE_URL
          valueFrom:
            secretKeyRef:
              name: cart-secret
              key: PRODUCT_SERVICE_URL

---
