# Use a lightweight official Python image
FROM python:3.13-slim

# Set work directory
WORKDIR /app

# Copy everything into container
COPY . .

# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Expose port 5000 (Flask default)
EXPOSE 5000

# Run the app
CMD ["python", "run.py"]
